name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APT_CACHE_DIR: ${{ github.workspace }}/.cache/apt/archives
    steps:
      - uses: actions/checkout@v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: ruby/Gemfile
        with:
          ruby-version: 4.0.0
          bundler-cache: true
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: .cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-apt-
      - name: Bootstrap
        run: make bootstrap
      - name: Prepare apt cache
        run: |
          sudo rm -f .cache/apt/archives/lock
          sudo chown -R "$USER":"$USER" .cache/apt
      - name: Run tests
        run: make
